receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # Exporter untuk metrics ke Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Exporter untuk traces ke Tempo
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

  # (Opsional) Exporter logging untuk debugging
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
